---
- hosts: all
  become: yes
  tasks:
  - name: Set hostname
    ansible.builtin.hostname:
      name: "{{ inventory_hostname }}"

  - name: Install overlay package
    community.general.rpm_ostree_pkg:
      name: "{{ item }}"
      state: present
    loop:
      - kubelet
      - kubeadm
      - cri-o

  
  # - name: Put SELinux in permissive mode, logging actions that would be blocked.
  #   ansible.posix.selinux:
  #     policy: targeted
  #     state: permissive



- hosts: master
  become: yes
  tasks:
    - name: Install overlay package
      community.general.rpm_ostree_pkg:
        name: kubectl
        state: present

    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 300
        reboot_msg: "Reboot initiated by Ansible for kernel update"

    - name: Enable and start kubelet service
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - cri-o
        - kubelet

    - name: Initialize Kubernetes master
      command: kubeadm init --pod-network-cidr=10.244.0.0/16 --cri-socket=/var/run/crio/crio.sock
      register: kubeadm_output
      ignore_errors: yes

    - name: Create join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Set global variable for join command
      set_fact:
        join_command: "{{ join_command.stdout }}"

    - name: Set up kubectl for the current user
      command: "{{ item }}"
      with_items:
        - "mkdir -p $HOME/.kube"
        - "cp /etc/kubernetes/admin.conf $HOME/.kube/config"
        #- "chown $(id -u):$(id -g) $HOME/.kube/config"
      ignore_errors: yes

    - name: Install kube-router
      command: kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml

- hosts: workers
  become: yes
  tasks:
    - name: Reboot the system
      ansible.builtin.reboot:
        reboot_timeout: 300
        reboot_msg: "Reboot initiated by Ansible for kernel update"

    - name: Enable and start kubelet service
      service:
        name: "{{ item }}"
        enabled: yes
        state: started
      loop:
        - cri-o
        - kubelet

    - name: Show join command
      debug:
        var: hostvars['master']['join_command']


    - name: Join worker nodes to the cluster
      command: "{{ hostvars['master']['join_command'] }}"
      

- hosts: all
  become: yes
  tasks:
  - name: Remove subscription.
    community.general.redhat_subscription:
      state: absent

